### ISSUE TITLE
[KK] [Currently patched] CharaMaker accs menu blank and inaccessible (v1.2.1.7)

### ISSUE THREAD

**Issue by Jatts-Art** [Prolo1/Character-Morpher#17]
I've been busy this past week so i didnt notice this beforehand... but now the accs menu no longer works with your newest version....

![5671a8526481b028fcf3cb894aa291af](https://github.com/Prolo1/Character-Morpher/assets/12752293/480929a7-3a23-489a-b129-6383849def7f)

**Comment by Gylthas** [comment]
I'm also facing this issue with the accessories menu not working at all, it wasn't happening with the first version of the plugin. 

I'm having issues with the issues that Jatts mentioned on his previous thread too. The card loading screen acts weird and shows small sized cards on one side of the menu.

**Comment by Prolo1** [comment]
I'm not even sure how that happened 🤔. I'll try to figure it out today since I missed seeing the bug for so long.

**Comment by Prolo1** [comment]
at the very least it doesn't seem to be the code for the UI change I made before.

**Comment by Prolo1** [comment]
Alright, this is kinda ridiculous. So the code that ultimately made loading a lot faster also causes the Accessary menu to be invisible for NO reason. 
This is the code:
https://github.com/Prolo1/Character-Morpher/blob/fc9414abe19e296836413d4fec8b9411de130d8e/Common/CharaMorpher.cs#L2320C3-L2330C4

https://github.com/Prolo1/Character-Morpher/blob/fc9414abe19e296836413d4fec8b9411de130d8e/Common/CharaMorpher.cs#L2361C3-L2405C1

that's all I use it for

There is no reference to the accessory menu anywhere nor do I disable any UI elements. Using the built-in unity function works when I switch but the lag issue happens like before... I'll just push out a version with the new UI disabled for now while I fix this.

**Comment by Prolo1** [comment]
Also before I forget, Thanks for the report!

**Comment by Jatts-Art** [comment]
Alrighty, I shall give it a test!

**Comment by Jatts-Art** [comment]
The fix you did seems to have worked, thank you!

There is another issue i wanted to bring up, but i am unsure if its even an issue to begin with or if this was intentional... But the slider settings dont seem to be the way they were before. For example the "Other" slider under the ABMX sliders seems to now squish the head when referencing my body templates for morphing, when before this did not happen.

v1.2.1.7:
![image](https://github.com/Prolo1/Character-Morpher/assets/12752293/446982b7-e4cd-4481-b142-5c67fffd561f)

v1.1.0:
![image](https://github.com/Prolo1/Character-Morpher/assets/12752293/776e8973-3abb-4b3f-9955-85aced8a7242)

I can work around this issue, not really a problem, but I wanted to bring this up anyway just in case this wasn't intended. Other than that, I think things seem to be fine (for now).

**Comment by Prolo1** [comment]
Ya I did start to notice that too, It is most likely an effect of some changes I've made in reading ABMX data so I'll look into it while I'm doing this.

**Comment by Jatts-Art** [comment]
I also get this error message now, whenever saving/loading coordinates, did not happen at all before. It does go away after reloading the card, but comes back if saving again. It also always says "#1" regardless of what outfit im on.

![99b75de21f4b56f9174da74149ebd22d](https://github.com/Prolo1/Character-Morpher/assets/12752293/1ffbe2df-334d-4db8-abb1-ee523e19ad89)

**Comment by Prolo1** [comment]
I do not touch coordinate data so I'm not sure what is causing that. you can send the log file (`game root/output_log.txt` if you're unfamiliar) and I can at least tell you what may be causing it / can't read it.

**Comment by Jatts-Art** [comment]
> I do not touch coordinate data so I'm not sure what is causing that. you can send the log file (`game root/output_log.txt` if you're unfamiliar) and I can at least tell you what may be causing it / can't read it.

Doesn't seem to be happening all the time, but the next time it occurs i'll disable CharaMorph and see if it relates or not. If i learn anything new i'll let you know at that time and share an output log.

> Ya I did start to notice that too, It is most likely an effect of some changes I've made in reading ABMX data so I'll look into it while I'm doing this.

As for this, would be great if you did because now I am realizing this is indeed a bit of an annoying issue when it comes to using the percentage buttons. I like using those for quick applying, so yah I wish you luck with looking into that!

The main focus of this thread is dealt with for now, so I'll go ahead and close this. Thanks again for the help!
