### ISSUE TITLE
Koikatsu Character Morphed and Plugin not working

### ISSUE THREAD

**Issue by Smuggish** [Prolo1/Character-Morpher#20]
![Screenshot 2024-08-06 033647](https://github.com/user-attachments/assets/09dd7250-c80f-4f45-aaeb-eccc702b0b7d)
It keeps resetting the Character's Body please help me

**Comment by Prolo1** [comment]
Thanks for letting me know! Could you tell me more details about what happens when you get the error, and also send me the `output_log.txt` file in your game directory after that error occurs if you can (It would help me speed things up).

**Comment by Prolo1** [comment]
it would also be nice to know what version of Character Morpher you are running.

**Comment by Prolo1** [comment]
If ya don't respond back in a week I'm closing the issue

**Comment by Prolo1** [comment]
and now closed
