### ISSUE TITLE
Saving the modified card to make changes permament?

### ISSUE THREAD

**Issue by wooshaq** [Prolo1/Character-Morpher#21]
Sorry, i'm not sure how this plugin works but I would like to apple changes and save the card to keep the modified body but upon load and disabling the plugin I get the original body, what option should I chose for it to work? I managed to save the changes like twice but I'm not sure what I did.

**Comment by Prolo1** [comment]
for that functionality, all you need to do is disable the "save ext. data" toggle and the the card will save like you expect. that toggle allows people to save the card w/o changing the original body so it will look the same when loaded the next time.

**Comment by Prolo1** [comment]
The mod has a lot of toggles (some of which I want to purge or make more intuitive), but they do allow for a lot of customization which is what I was aiming for. 

Feel free to open this reply again if this doesn't completely answer your question.

**Comment by Prolo1** [comment]
actually I think ill move this to discussions instead since it makes more sense for it to be there
