### ISSUE TITLE
ABMX morphing busted in HS2 (Maybe ABMX5 issue?)

### ISSUE THREAD

**Issue by Kayinnasaki** [Prolo1/Character-Morpher#7]
Hey, I've been unable to use sliders or get any ABMX changes to happen with this very neat seeming mod in HS2. I tested this with the most minimal setup possbile -- saved the default character with a few obvious bone morphs, no weird extra bones or accessories -- set as target, reset character and tried to get it to work, with no success. Non ABMX sliders work as expected. Messed with all the different checkboxes for ABMX just to see if anything ever worked or changed. Notably, I'm on ABMX5 which I know is still a beta I think, so it's understandable if you're not supporting it yet but I figured I'd still give a heads up if this turns out to be the case.

Console also cranks out some errors that are variations of this, which might be helpful.

```[Error  : Unity Log] MissingMethodException: void KKABMX.Core.BoneModifier.Apply(KKABMX.Core.CoordinateType,System.Collections.Generic.IList`1<KKABMX.Core.BoneModifierData>,bool)
Stack trace:
Character_Morpher.CharaMorpherController.AbmxSettings (System.Boolean reset, System.Boolean initReset, KKABMX.Core.BoneController boneCtrl) (at <43e5a4e302564b5c957e3a3338ea7164>:0)
Character_Morpher.CharaMorpherController.MorphValuesUpdate (System.Boolean reset, System.Boolean initReset, System.Boolean abmx) (at <43e5a4e302564b5c957e3a3338ea7164>:0)
Character_Morpher.CharaMorpherController.MorphChangeUpdate (System.Boolean forceReset, System.Boolean initReset, System.Boolean updateValues, System.Boolean abmx) (at <43e5a4e302564b5c957e3a3338ea7164>:0)
Character_Morpher.CharaMorpherController+<CoMorphChangeUpdate>d__31.MoveNext () (at <43e5a4e302564b5c957e3a3338ea7164>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a43c47796b1b4dc78509dc74aec2356b>:0)```

**Comment by Prolo1** [comment]
I know exactly why that happens, it's because I used an older version of ABMX when I initially tested and since then things have changed. I updated the version in the project and should be done with a fix for it in a couple of hours once I'm done testing. thanks for the report!!!

**Comment by Prolo1** [comment]
It's done and works better than it should, but I'm not complaining ¯\_(ツ)_/¯. you should see it in a few minutes.

**Comment by Kayinnasaki** [comment]
Mod is working as expected! tysm for the fast turn-around time, gonna start playing around with it right now.
